[source.crates-io]
replace-with = 'rsproxy-sparse'
[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"
[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"
[registries.rsproxy]
index = "https://github.com/rust-lang/crates.io-index"
[net]
git-fetch-with-cli = true

[registries.crates-io]
protocol = "sparse"